### PR TITLE
Props panel refactoring

### LINKED ISSUE #1013: Props panel: user added properties
- [ ] Always show label (property name) as text rather than input 
- [ ] UI to add a property
- [ ] UI to remove a property
- [ ] Controls should be able to control their layout including position of label and delete button. Example: <br/>Screenshot 2023-02-13 at 11 18 30

----------------------------

User Added Properties

### LINKED ISSUE #1051: Doing ZOD validation on import seems like seriously blocks script startup times
Because of that we can't use react-sdk at cloudflare with Bundled/Unbound model and getting 

```
Error: Failed to publish your Function. Got error: Error: Script startup exceeded CPU time limit.
```

see [Worker startup time](https://developers.cloudflare.com/workers/platform/limits/#worker-startup-time) 

Example https://github.com/webstudio-is/webstudio-builder/blob/main/packages/react-sdk/src/components/body.ws.tsx#L62-L64

Having that it's our tool generates all that data we can use zod on write, not on read.

### PR DESCRIPTION
**Pull request by rpominov**
## Description

Closes #1013

1. Refactored `PropMeta` shape to be flat again instead of trying to be the same as Storybook's `ArgType`
2. Changed `*.props.json` to `*.props.ts`. Fixes #1051
3. Prepared controls files structure, now just need to work on their UI
4. Refactored `usePropsLogic/PropsPanel` to the new logic where we choose the prop before adding and then never change the name
5. A lot of cleanup / small fixes / better TS types

This PR basically completes architecture/logic and now only the work on the controls UI is left. Although complicated controls like URL may still require some work on the logic.

## Steps for reproduction

1. Open props panel
2. Interact with the props

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
- [ ] hi @istarkov, I need you to do
  - conceptual review (architecture, feature-correctness)
  

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-builder/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

File: packages/project-build/src/schema/props.ts [hunk 1]
```diff
@@ -30,6 +30,11 @@ export const Prop = z.union([
     type: z.literal("asset"),
     value: z.string(),
   }),
+  z.object({
+    ...baseProp,
+    type: z.literal("string[]"),
+    value: z.array(z.string()),
+  }),
```
Comment (rpominov) [inline packages/project-build/src/schema/props.ts:37]: @istarkov @TrySound 

Asking just in case: is it ok to add a new prop type "string[]"? Are there any concerns?

File: apps/builder/app/builder/features/props-panel/controls/combined.tsx [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+import { ColorControl } from "./color";
+import { NumberControl } from "./number";
+import { CheckControl } from "./check";
+import { RadioControl } from "./radio";
+import { SelectControl } from "./select";
+import { BooleanControl } from "./boolean";
+import { FileImageControl } from "./file-image";
+import type { ControlProps } from "../shared";
+
+export const CombinedControl = ({
```
Comment (kof) [inline apps/builder/app/builder/features/props-panel/controls/combined.tsx:11]: does this need to be a component or just a function that renders a component?

File: apps/builder/app/builder/features/props-panel/use-props-logic.ts [hunk 3]
```diff
@@ -1,156 +1,240 @@
...
+  // If undefined is returned,
+  // we will not add a prop in storage until we get an onChange from control.
+  //
+  // User may have this experience:
+  //   - they added a prop but didn't touch the control
+  //   - they closed props panel
+  //   - when they open props panel again, the prop is not there
+  //
+  // We want to avoid this if possible, but for some types like "asset" we can't
+  return undefined;
```
Comment (kof) [inline apps/builder/app/builder/features/props-panel/use-props-logic.ts:50]: Why would your return an undefined, its the default behavior? Needed someplace for the comment? How about about the function declaration

File: apps/builder/app/builder/features/props-panel/use-props-logic.ts [hunk 4]
```diff
@@ -1,156 +1,240 @@
...
+const getStartingProp = (
+  instanceId: Instance["id"],
+  meta: PropMeta,
+  name: string
+): Prop | undefined => {
+  const value = getStartingValue(meta);
+  return value && { id: nanoid(), instanceId, name, ...value };
+};
+
+const getDefaultMetaForType = (type: Prop["type"]): PropMeta => {
```
Comment (kof) [inline apps/builder/app/builder/features/props-panel/use-props-logic.ts:62]: seems like this could be just a map from type to meta instead of a function with all the ifs

e.g. 
```
typeToMetaMap = {asset: { type: "string", control: "file-image", required: false }}
```
Also, where is the type "asset" coming from, storybook calls it "file", wouldn't it make sense to call it file too? or is it deeply depending on our internal asset?

File: apps/builder/app/builder/features/props-panel/use-props-logic.ts [hunk 5]
```diff
@@ -1,156 +1,240 @@
...
-  };
+type UsePropsLogicOutput = {
+  /**
+   * Initial (not deletable) props
+   */
+  initialProps: PropAndMeta[];
+  /**
+   * Optional props that were added
+   */
+  optionalProps: PropAndMeta[];
```
Comment (kof) [inline apps/builder/app/builder/features/props-panel/use-props-logic.ts:103]: are those props added by the user or by the component? not clear from reading the comment

File: apps/builder/app/builder/features/props-panel/use-props-logic.ts [hunk 6]
```diff
@@ -1,156 +1,240 @@
...
+  /**
+   * Remaining props that can be added
+   */
+  remainingProps: NameAndLabel[];
```
Comment (kof) [inline apps/builder/app/builder/features/props-panel/use-props-logic.ts:107]: remaining sounds like its complete list of the entire remaining properties, if I understand correctly, its the properties that user has manually added? I think there is a better name once I understand the meaning of it

File: apps/builder/app/builder/features/props-panel/controls/combined.tsx (hunk 2 above)
Comment (rpominov) [reply apps/builder/app/builder/features/props-panel/controls/combined.tsx:11]: What is the difference? Is there an issue with it being a component?

File: apps/builder/app/builder/features/props-panel/use-props-logic.ts [hunk 7]
```diff
@@ -1,156 +1,240 @@
...
-      addedPropsById.set(prop.id, prop);
-      continue;
+
+    return { prop, propName: name, meta: known };
+  });
+
+  // names of the props added by the user during the lifetime of the hook
+  const [newNames, setNewNames] = useState<Prop["name"][]>([]);
+
+  const oldOptional: PropAndMeta[] = [...unprocessedSaved.values()]
```
Comment (kof) [inline apps/builder/app/builder/features/props-panel/use-props-logic.ts:168]: isn't values() already returning a new array essentially, why clone it?

Comment (kof) [reply apps/builder/app/builder/features/props-panel/use-props-logic.ts:168]: ah sorry, its an iterator convertion to array, maybe better Array.from() to be clear

File: apps/builder/app/builder/features/props-panel/use-props-logic.ts (hunk 3 above)
Comment (rpominov) [reply apps/builder/app/builder/features/props-panel/use-props-logic.ts:50]: Ah. I'm just not used to use `udefined` and always forget you don't have to return it explicitly.

But yeah, in this case it's also better place for the comment IMO. Can put on the top though, not a strong opinion.

File: packages/generate-arg-types/src/arg-types.ts [hunk 8]
```diff
@@ -44,43 +44,64 @@ const matchers = {
...
+        // @todo: we need some checks here. for example type.name can be "ImageLoader"
+        return makePropMeta("string", "text");
     }
-    case "function":
-    case "symbol":
-      return;
-    default:
-      // @todo: we need some checks here. for example type.name can be "ImageLoader"
-      return PropMeta.parse({ ...common(), control: "text" });
+  } catch (e) {
```
Comment (kof) [inline packages/generate-arg-types/src/arg-types.ts:102]: no shorthands (I know it was there before)
```suggestion
  } catch (error) {
```

**Comment by kof** [comment]
After image selection on Source property

Screenshot 2023-02-22 at 10 48 57

File: apps/builder/app/builder/features/props-panel/controls/combined.tsx (hunk 2 above)
Comment (kof) [reply apps/builder/app/builder/features/props-panel/controls/combined.tsx:11]: Component goes through react render circle, its way slower than just a function, do it only if you actually need a component

File: apps/builder/app/builder/features/props-panel/use-props-logic.ts (hunk 5 above)
Comment (rpominov) [reply apps/builder/app/builder/features/props-panel/use-props-logic.ts:103]: By user. Fixed the comment

File: apps/builder/app/builder/features/props-panel/use-props-logic.ts (hunk 4 above)
Comment (kof) [reply apps/builder/app/builder/features/props-panel/use-props-logic.ts:62]: wrapping into a function is fine, but ifs instead of a simple map looks fishy, because you don't seem to need custom logic there, its just a switch/case type of thing going on here

File: apps/builder/app/builder/features/props-panel/use-props-logic.ts (hunk 6 above)
Comment (rpominov) [reply apps/builder/app/builder/features/props-panel/use-props-logic.ts:107]: It's the complete list of the remaining props still available to add

Comment (kof) [reply apps/builder/app/builder/features/props-panel/use-props-logic.ts:107]: that makes sense then, better to clarify this in the comment, I was not sure

File: apps/builder/app/builder/features/props-panel/use-props-logic.ts (hunk 5 above)
Comment (kof) [reply apps/builder/app/builder/features/props-panel/use-props-logic.ts:103]: I think I got confused because optional doesn't imply its controlled/added by the user, maybe better userProps? customProps?

**Comment by rpominov** [comment]
> After image selection on Source property

All UI is temporary in this PR

File: apps/builder/app/builder/features/props-panel/use-props-logic.ts (hunk 5 above)
Comment (kof) [reply apps/builder/app/builder/features/props-panel/use-props-logic.ts:103]: addedProps?

**Review by kof — APPROVED** [review]
Good work, approving upfront, most issues are semantics

File: apps/builder/app/builder/features/props-panel/controls/combined.tsx (hunk 2 above)
Comment (rpominov) [reply apps/builder/app/builder/features/props-panel/controls/combined.tsx:11]: By that logic we should rewrite all our components that don't use hooks as functions. Sounds crazy :)

File: apps/builder/app/builder/features/props-panel/use-props-logic.ts (hunk 4 above)
Comment (rpominov) [reply apps/builder/app/builder/features/props-panel/use-props-logic.ts:62]: re-wrote with switch/case

File: apps/builder/app/builder/features/props-panel/controls/combined.tsx (hunk 2 above)
Comment (kof) [reply apps/builder/app/builder/features/props-panel/controls/combined.tsx:11]: depends, if you need component in the component tree for debugging purposes or because it needs a state - component is the way to go, but when its just a simple render function that doesn't need to be in the tree and will only make the tree less readable - why making it component

Comment (rpominov) [reply apps/builder/app/builder/features/props-panel/controls/combined.tsx:11]: https://discord.com/channels/955905230107738152/1077912355087863919
