### PR TITLE
Fix build permission not work on page change inside builder

### LINKED ISSUE #1063: Build permission seems to not apply to other pages
Repro
- Create a project, 
- create a sharable link with build permissions
- Add a second page
- Open incognito mode the link with build permission
- Open pages sidebar and switch to the second page

Screenshot 2023-02-17 at 19 35 23

### PR DESCRIPTION
**Pull request by istarkov**
## Description

1. What is this PR about (link the issue and add a short description)

closes #1063

## Steps for reproduction

1. click button
2. expect xyz

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-builder/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

File: apps/builder/app/shared/nano-states/nano-states.ts [hunk 1]
```diff
@@ -326,6 +326,14 @@ export const useSetAuthPermit = (authPermit: AuthPermit) => {
   });
 };
 
+const authTokenStore = atom<string | undefined>(undefined);
+export const useAuthToken = () => useValue(authTokenStore);
+export const useSetAuthToken = (authToken: string | undefined) => {
```
Comment (kof) [inline apps/builder/app/shared/nano-states/nano-states.ts:331]: I think you can add the store to registerContainers and put it into a  /shared/nano-states so that it's automatically synced

Comment (istarkov) [reply apps/builder/app/shared/nano-states/nano-states.ts:331]: No need in sync, canvas has view access always

**Review by kof — APPROVED** [review]
