### PR TITLE
Ability to link by #ID; Fixed a bug with links in RTE

### LINKED ISSUE #991: Props panel: always show ID
Screenshot 2023-02-10 at 16 26 29

- [ ] Make sure all our components can take an `id` prop and pass it to `<element id=`
- [ ] Add `id` prop to "always visible" in all components

Not essential:

- [ ] Show a error if `id` is not unique across all components on the page
- [ ] Always show `id` first and add a separator after it
- [ ] Custom label `ID` instead of `Id`

### LINKED ISSUE #993: Props panel: control type URL
Screenshot 2023-02-10 at 17 08 49

- [x] Add control type URL and use it for `Link.href`
- [x] Ability to enter arbitrary url
- [x] Ability to choose a page
- [x] Make sure to call onChange at `blur` when user enters URL

Not essential:

- [ ] Section link
- [x] Email link
- [x] Phone link
- [x] Attachment link

Link Properties

### LINKED ISSUE #1380: RTE link styling regression
When editing RTE, link suddenly gets different styles than after exiting editing mode

https://user-images.githubusercontent.com/52824/230070052-df32dec5-b3a1-460d-a41d-dde94eb08e70.mp4

### LINKED ISSUE #1475: Ability to link to a section on a specific page
Context: https://github.com/webstudio-is/webstudio-builder/pull/1454#issuecomment-1511164203

We should consider an ability to create a link to a specific section on a specific page. Perhaps have a section picker next to the page picker here:

Screenshot 2023-04-17 at 14 54 21

### PR DESCRIPTION
**Pull request by rpominov**
## Description

1. Made `href` always present (# is used when not set, similar to Webflow). Fixes #1380
2. Added "Section" option in URL Control. Closes #993 
3. Added "ID" prop that is visible in all components. Closes #991 
4. Closes #1475

## Steps for reproduction

1. Add ID prop to an instance
4. Add a link that references that instance by ID

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
- [ ] hi @TrySound, I need you to
  - have a look at how I deal with stores to get list of available IDs

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-builder/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

File: apps/builder/app/builder/features/props-panel/controls/url.tsx [hunk 1]
```diff
@@ -211,9 +222,94 @@ const BaseAttachment = ({ prop, onChange, onSoftDelete }: BaseControlProps) => (
   </Row>
 );
 
+// store that contains IDs off all instances in the selected page
+const pageInstancesStore = computed(
```
Comment (kof) [inline apps/builder/app/builder/features/props-panel/controls/url.tsx:226]: this could be useful globally I guess, no? I have a feeling we must be potentially even doing this already somewhere @TrySound

File: apps/builder/app/builder/features/props-panel/controls/url.tsx [hunk 2]
```diff
@@ -211,9 +222,94 @@ const BaseAttachment = ({ prop, onChange, onSoftDelete }: BaseControlProps) => (
...
+      }
+    }
+
+    return sections;
+  }
+);
+
+// too hard to mock all the stores that sectionsStore is derived from
+// so we have this for Storybook
+export const setMockUrlSectionsStore = (store: typeof sectionsStore) => {
```
Comment (kof) [inline apps/builder/app/builder/features/props-panel/controls/url.tsx:275]: another option is to pass the sections to a component <Components sections={sectionsStore.get()} /> 
So this way when you need to mock it, you pass it directly to the component, I just ended up doing this in BreakpointsSelector

I created a BreakpointsSelectorContainer that holds the stores, so I can have a pure BreakpointsSelector I can render in stories

File: apps/builder/app/builder/features/props-panel/props-panel.stories.tsx [hunk 3]
```diff
@@ -40,6 +42,13 @@ pagesStore.set({
...
 
+const urlSections = new Map([
+  [unique(), "links"],
+  [unique(), "about"],
+]);
+
+setMockUrlSectionsStore(atom(urlSections));
+
 const imageAsset = (name = "cat", format = "jpg"): Asset => ({
   id: unique(),
```
Comment (kof) [inline apps/builder/app/builder/features/props-panel/props-panel.stories.tsx:53]: wouldn't it be better to just use nanoid everywhere instead of unieque?

**Comment by kof** [comment]
I just realized that it's impossible to link using a section on a different page. Same problem at webflow. How did we not see that upfront?
It seems that the right place for this action is under the page tab, where you can either choose a page, or section or both

cc @taylornowotny

**Review by kof — APPROVED** [review]

File: apps/builder/app/builder/features/props-panel/controls/url.tsx (hunk 1 above)
Comment (rpominov) [reply apps/builder/app/builder/features/props-panel/controls/url.tsx:226]: Yeah, wasn't sure about this too. @TrySound What do you think?

File: apps/builder/app/builder/features/props-panel/controls/url.tsx (hunk 2 above)
Comment (rpominov) [reply apps/builder/app/builder/features/props-panel/controls/url.tsx:275]: In this case we would have to pass this prop to `<PropsPanel>`, which feels front from the separations of concerns point of view.

Comment (kof) [reply apps/builder/app/builder/features/props-panel/controls/url.tsx:275]: yeah, not great, but we should have a general internal standard for mocking stores, so that we don't end up having hundreds of mock functions

Comment (kof) [reply apps/builder/app/builder/features/props-panel/controls/url.tsx:275]: maybe @TrySound has an opinion on this

**Comment by rpominov** [comment]
> I just realized that it's impossible to link using a section on a different page

Created an issue: #1475

File: apps/builder/app/builder/features/props-panel/props-panel.stories.tsx (hunk 3 above)
Comment (rpominov) [reply apps/builder/app/builder/features/props-panel/props-panel.stories.tsx:53]: Ah, just realised it will not work, because IDs are visible in lostpixel screenshot and have to be stable

File: apps/builder/app/builder/features/props-panel/controls/url.tsx (hunk 1 above)
Comment (TrySound) [reply apps/builder/app/builder/features/props-panel/controls/url.tsx:226]: See findTreeInstanceIds in project-build

File: apps/builder/app/builder/features/props-panel/props-panel.stories.tsx [hunk 4]
```diff
@@ -40,6 +42,13 @@ pagesStore.set({
   ],
 });
 
+const urlSections = new Map([
+  [unique(), "links"],
+  [unique(), "about"],
+]);
+
+setMockUrlSectionsStore(atom(urlSections));
```
Comment (TrySound) [inline apps/builder/app/builder/features/props-panel/props-panel.stories.tsx:50]: I see no problem in mocking writable atoms. We would have testing element here.

I usually add createInstancePair and createPropPair utilities to make formatting better and not duplicate id

```ts
pagesStore.set({
  homePage: { id: 'home', rootInstanceId: 'root' }
  pages: []
})
instances.set(new Map([
  ['root', {
    id: 'root',
    component: 'Box',
    children: []
  }]
]))
props.set(new Map([
  ['prop1', {
    type: "string",
    name: "id",
    value: "links",
    instanceId: 'root'
  }],
  ['prop3', {
    type: "string",
    name: "id",
    value: "about",
    instanceId: 'root'
  }],
]))
```

**Review by TrySound — APPROVED** [review]

**Comment by rpominov** [comment]
@kof @taylornowotny Please test how page / section select works in the video or in preview:

https://user-images.githubusercontent.com/825702/232760359-2628cd49-f725-4425-864e-0d6ad68db03e.mov

**Comment by taylornowotny** [comment]
@rpominov This is perfect - great job! 🔥 I'm impressed that you figured out the ideal UX without those details being provided in the design.

**Comment by kof** [comment]
nice

File: apps/builder/app/builder/features/props-panel/controls/url.tsx [hunk 5]
```diff
@@ -175,29 +186,104 @@ const BaseEmail = ({ prop, onChange, id }: BaseControlProps) => {
   );
 };
 
+const useSections = (page: { rootInstanceId: string }) => {
+  const store = useMemo(
+    () =>
+      computed([instancesStore, propsStore], (instances, props) => {
```
Comment (kof) [inline apps/builder/app/builder/features/props-panel/controls/url.tsx:192]: hmm, not sure why you need computed, seems like you could just call .get() on those stores

File: apps/builder/app/builder/features/props-panel/use-props-logic.ts [hunk 6]
```diff
@@ -113,9 +108,20 @@ const getAndDelete = <Value>(map: Map<string, Value>, key: string) => {
...
- */
+const systemPropsMeta: { name: string; meta: PropMeta }[] = [
+  {
+    name: "id",
+    meta: {
+      required: false,
+      control: "text",
+      type: "string",
+      rows: 0,
+      label: "ID",
```
Comment (kof) [inline apps/builder/app/builder/features/props-panel/use-props-logic.ts:119]: Id?

File: apps/builder/app/builder/features/props-panel/controls/url.tsx (hunk 5 above)
Comment (rpominov) [reply apps/builder/app/builder/features/props-panel/controls/url.tsx:192]: I call `useStore()` on the `store` created by `computed`. `computed` inside `useMemo` is a pattern we use everywhere

File: packages/react-sdk/src/components/link.tsx [hunk 7]
```diff
@@ -19,10 +19,14 @@ export const Link = forwardRef<HTMLAnchorElement, Props>((props, ref) => {
 
   const { assetBaseUrl } = getParams();
 
-  let url: string | undefined;
+  let url = "#";
+
   switch (href?.type) {
     case "page":
       url = href.page.path;
+      if (href.idPropValue !== undefined) {
```
Comment (kof) [inline packages/react-sdk/src/components/link.tsx:27]: why not href.hash // "#asdfasdf"

like .hash in new URL()

**Comment by rpominov** [comment]
> One point of feedback - the select button that says 'Current Page' is showing placeholder text. Current Page is a pre-selected option from the menu, not placeholder text, so for this we would use the "set value" state rather than the "placeholder" state (or whatever equivalent you have on the code component).

We show it as a placeholder currently, because when it says "Current Page" prop is not yet set to link to the current page.

The text "Current Page" is here only to let user know that the sections list is from the current page if they don't select a specific page.

We could instead actually pre-select current page at the moment user switches to the "Page" tab, but then logic of entire URL control changes: currently switching between tabs doesn't change the prop value. This allows to explore tabs w/o loosing value set in the different tab.

**Review by kof — APPROVED** [review]
really don't like the idPropValue name, otherwise great

**Comment by taylornowotny** [comment]
@rpominov Good ideas.

Is this pattern reasonable?

Change it to "Choose page" (placeholder state)
Section menu lists all sections that have an ID on all pages
Choosing a section without choosing a page first will select the page that the section is on

This seems like the ideal UX but if that won't work then we can leave it as is.

**Comment by rpominov** [comment]
> Section menu lists all sections that have an ID on all pages
Choosing a section without choosing a page first will select the page that the section is on

Ah, great idea! Shouldn't be a problem, will do.
