### PR TITLE
Fix collapse

### LINKED ISSUE #1087: Collapsing box outline bugs
1. wrong detection after reload

- add box1 > box2
- reload 
- both boxes are outlined, but only box2 one should have outline

2. box collapses on height, but spacing added on width

- add box1 > box2
- set height: 200 on box1
- set display: flex on box1
- we detect horizontal collapse on box 2, but height is 0 because of parent flex

### PR DESCRIPTION
**Pull request by istarkov**
## Description

closes #1087 

- [x] found bug we should not remove all collapsed
- [x] we need to detect edge-case if element explicitly has 0 width / height

## Steps for reproduction

see #1087

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-builder/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

File: apps/builder/app/builder/builder.tsx [hunk 1]
```diff
@@ -74,7 +75,7 @@ const useNavigatorLayout = () => {
   // We need to render the detached state only once the setting was actually loaded from local storage.
   // Otherwise we may show the detached state because its the default and then hide it immediately.
   const [clientSettings, _, isLoaded] = useClientSettings();
-  return isLoaded ? clientSettings.navigatorLayout : "docked";
+  return isLoaded ? clientSettings.navigatorLayout : "undocked";
```
Comment (kof) [inline apps/builder/app/builder/builder.tsx:78]: please don't change this behavior by default, we want users to have navigator undocked by default because that's the most common need, in reality people use it all the time

File: apps/builder/app/builder/builder.tsx [hunk 2]
```diff
@@ -333,6 +334,7 @@ export const Builder = ({
               css={{
                 height: "100%",
                 width: "100%",
+                minWidth: `${minWidth}px`,
```
Comment (kof) [inline apps/builder/app/builder/builder.tsx:337]:
```suggestion
                minWidth,
```

File: apps/builder/app/builder/builder.tsx (hunk 1 above)
Comment (istarkov) [reply apps/builder/app/builder/builder.tsx:78]: undocked.
image

docked
image

I see the same picture but in the case of "undocked" there is no layout trash
So I'm not getting why I can't change it

Comment (kof) [reply apps/builder/app/builder/builder.tsx:78]: ohh, I thought you changed the other way around, but also, did you try to set it do docked on the client and reload? now it should be loading as undocked with your change and then jumping to docked

Comment (kof) [reply apps/builder/app/builder/builder.tsx:78]: probably we should just add a transition for this so that this doesn't feel like a jump but rather as a nice, wanted transition

File: apps/builder/app/canvas/collapsed.ts [hunk 3]
```diff
@@ -0,0 +1,122 @@
+import { collapsedAttribute } from "@webstudio-is/react-sdk";
```
Comment (kof) [inline apps/builder/app/canvas/collapsed.ts:1]: could probably go to ./shared/collapse-detection.ts

File: apps/builder/app/canvas/collapsed.ts [hunk 4]
```diff
@@ -0,0 +1,122 @@
...
+  instanceIdSet.clear();
+  if (instanceIds.length === 0) {
+    return;
+  }
+
+  /**
+   *  Selector to find element itself or common ancestor
+   *  (finding common ancestor is suboptimal solution but it almost never happens)
+   **/
+  const eltSelector =
```
Comment (kof) [inline apps/builder/app/canvas/collapsed.ts:17]:
```suggestion
  const elementSelector =
```

File: apps/builder/app/canvas/collapsed.ts [hunk 5]
```diff
@@ -0,0 +1,122 @@
...
+
+  const elementsToRecalculate: HTMLElement[] = [];
+  const parentsWithAbsoluteChildren = new Map<HTMLElement, number>();
+
+  for (const element of elements) {
+    if (!(element instanceof HTMLElement)) {
+      continue;
+    }
+
+    if (element.tagName === "_IMG") {
```
Comment (kof) [inline apps/builder/app/canvas/collapsed.ts:42]: I think we should ignore all void elements https://developer.mozilla.org/en-US/docs/Glossary/Void_element

File: apps/builder/app/canvas/collapsed.ts [hunk 6]
```diff
@@ -0,0 +1,122 @@
...
+    // Find all Leaf like elements
+    // Leaf like elements are elements that have no children or all children are absolute or fixed
+    if (element.childElementCount === 0) {
+      elementsToRecalculate.push(element);
+    }
+
+    const elementPosution = window.getComputedStyle(element).position;
+
+    if (elementPosution === "absolute" || elementPosution === "fixed") {
+      if (element.parentElement) {
```
Comment (kof) [inline apps/builder/app/canvas/collapsed.ts:59]: this condition should be around the entire block

File: apps/builder/app/canvas/collapsed.ts [hunk 7]
```diff
@@ -0,0 +1,122 @@
...
+      elementsToRecalculate.push(element);
+    }
+  }
+
+  // Now combine all operations in batches.
+
+  // 1. Remove all collapsed attributes
+  baseElement.parentElement?.removeAttribute(collapsedAttribute);
+  baseElement.removeAttribute(collapsedAttribute);
+  for (const elt of baseElement.querySelectorAll(`[${collapsedAttribute}]`)) {
```
Comment (kof) [inline apps/builder/app/canvas/collapsed.ts:84]:
```suggestion
  for (const element of baseElement.querySelectorAll(`[${collapsedAttribute}]`)) {
```

File: apps/builder/app/canvas/canvas.tsx [hunk 8]
```diff
@@ -120,6 +122,29 @@ export const Canvas = ({
...
+            const instanceId = patch.value?.instanceId;
+
+            if (typeof instanceId === "string") {
+              setDataCollapsed(instanceId);
+            }
+          }
+        }
+      }
+    });
+  }, [data.tree?.root.id]);
```
Comment (kof) [inline apps/builder/app/canvas/canvas.tsx:146]: - lets move this as a custom hook into collapsed
- separate react from non-react - everything inside useEffect is non-react, make a separate function and call it from the hook

File: apps/builder/app/canvas/collapsed.ts [hunk 9]
```diff
@@ -0,0 +1,122 @@
...
+  elements.push(baseElement);
+
+  const descendants = baseElement.querySelectorAll("[data-ws-id]");
+  elements.push(...descendants);
+
+  const elementsToRecalculate: HTMLElement[] = [];
+  const parentsWithAbsoluteChildren = new Map<HTMLElement, number>();
+
+  for (const element of elements) {
+    if (!(element instanceof HTMLElement)) {
```
Comment (kof) [inline apps/builder/app/canvas/collapsed.ts:38]: I think you can also check nodeType, seems better than instance checks

Comment (kof) [reply apps/builder/app/canvas/collapsed.ts:38]: nodeType === Node.ELEMENT_NODE

File: apps/builder/app/canvas/collapsed.ts [hunk 10]
```diff
@@ -0,0 +1,122 @@
...
+
+    // Find all Leaf like elements
+    // Leaf like elements are elements that have no children or all children are absolute or fixed
+    if (element.childElementCount === 0) {
+      elementsToRecalculate.push(element);
+    }
+
+    const elementPosution = window.getComputedStyle(element).position;
+
+    if (elementPosution === "absolute" || elementPosution === "fixed") {
```
Comment (kof) [inline apps/builder/app/canvas/collapsed.ts:58]: typo

File: apps/builder/app/builder/builder.tsx (hunk 1 above)
Comment (istarkov) [reply apps/builder/app/builder/builder.tsx:78]: I think we should move docked/undocked into searchParams. Or switch on client rendering. Transitions doesn't look good.

File: apps/builder/app/canvas/collapsed.ts (hunk 3 above)
Comment (istarkov) [reply apps/builder/app/canvas/collapsed.ts:1]: Do we need this to be used elsewhere?

File: apps/builder/app/builder/builder.tsx (hunk 1 above)
Comment (kof) [reply apps/builder/app/builder/builder.tsx:78]: searchParams won't solve it for permanently setting it, I think we could save it in the db, then ssr knows the setting

Comment (kof) [reply apps/builder/app/builder/builder.tsx:78]: but this problem is just one case, we will have more later, so we need a way to allow local settings based on local storage I think

File: apps/builder/app/canvas/collapsed.ts (hunk 3 above)
Comment (kof) [reply apps/builder/app/canvas/collapsed.ts:1]: nope, in that case features/collapse-detection

**Review by kof — APPROVED** [review]

File: apps/builder/app/canvas/canvas.tsx (hunk 8 above)
Comment (TrySound) [reply apps/builder/app/canvas/canvas.tsx]: This is very hacky assumption and will break next week. Let's move it back to hurt everyone's eyes.

Comment (istarkov) [reply apps/builder/app/canvas/canvas.tsx]: Just keep in mind that we need to somehow know what instanceId was affected by the style change.

Comment (TrySound) [reply apps/builder/app/canvas/canvas.tsx]: The issue is that token style can affect a few instances. Not just one.
