### PR TITLE
Fix Escape and Enter issues

### LINKED ISSUE #1359: Clicking "esc" hides style panel
To reproduce select any element, and click esc, element looks like selected but Style Panel is not visible. 
This also causes bugs when you edit something from the keyboard, esc causes style panel to close

https://user-images.githubusercontent.com/5077042/229519551-4d475414-cb41-4bdb-8c06-2f7bed56eda9.mov

Double Esc here 

Single Esc here 

Single esc when unit selected
image

### PR DESCRIPTION
**Pull request by istarkov**
## Description

closes #1359

The only Esc event that needed to be passed into Canvas from the builder is cancelCurrentDrag (don't know why)

- [x] - Todo reset/notshow outline on canvas Escape click too to have visual response
- [x] - Fix Enter to work only in Navigator

## Steps for reproduction

See corresponding issue #1359 . 

## Code Review
- [x] hi @kof , I need you to do
  - test it on preview

- [x] hi @TrySound , I need you to do
  - detailed review (read every line)

## Before requesting a review

- [x] made a self-review
- [x] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [x] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-builder/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

File: apps/builder/app/canvas/use-canvas-shortcuts.ts [hunk 1]
```diff
@@ -2,7 +2,10 @@ import { useHotkeys } from "react-hotkeys-hook";
 import { shortcuts, options } from "~/shared/shortcuts";
```
Comment (TrySound) [inline apps/builder/app/canvas/use-canvas-shortcuts.ts:2]: Let's call this just canvas-shortcuts.ts in case we get rid of react package here

File: apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts [hunk 2]
```diff
@@ -113,6 +113,7 @@ export const SelectedInstanceConnector = ({
     selectedInstanceIntanceToTagStore.set(instanceToTag);
 
     return () => {
+      hideOutline();
```
Comment (TrySound) [inline apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts:116]: Can't this lead to race condition when other element is selected?

Comment (istarkov) [reply apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts:116]: Should not, as unsubscribe happens before subscribe

File: apps/builder/package.json [hunk 3]
```diff
@@ -68,6 +68,7 @@
     "lodash.debounce": "^4.0.8",
     "match-sorter": "^6.3.1",
     "mdast-util-from-markdown": "^1.3.0",
+    "merge-refs": "^1.1.3",
```
Comment (TrySound) [inline apps/builder/package.json:71]: react-aria/utils has merge-refs

File: apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts (hunk 2 above)
Comment (TrySound) [reply apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts:116]: But you batch events. Is there a guarantee sent events have the same order on the other side?

File: apps/builder/package.json (hunk 3 above)
Comment (kof) [reply apps/builder/package.json:71]: we already use it from react-aria

Comment (istarkov) [reply apps/builder/package.json]: done

File: pnpm-lock.yaml [hunk 4]
```diff
@@ -12684,6 +12772,38 @@ packages:
       tapable: 1.1.3
       typescript: 5.0.3
       webpack: 4.46.0
+    dev: false
+
+  /fork-ts-checker-webpack-plugin@6.5.2(typescript@5.0.3)(webpack@4.46.0):
```
Comment (TrySound) [inline pnpm-lock.yaml:12777]: A lot unnecessary updates. Please revert lock file and install again.

**Review by TrySound — APPROVED** [review]

**Comment by kof** [comment]
I tried opening the deployment, it says:
```
This Serverless Function has crashed.

Your connection is working correctly.

Vercel is working correctly.

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: fra1:fra1::8r9mm-1680702130715-48da5831998f
```

File: apps/builder/app/builder/shared/shortcuts/use-publish-shortcuts.ts [hunk 5]
```diff
@@ -30,3 +34,32 @@ export const usePublishShortcuts = (publish: Publish) => {
     );
   });
 };
+
+/**
+ * Forwarding shortcuts to the canvas.
+ */
+export const usePublishInstanceTreeShortcuts = <T extends HTMLElement>(
```
Comment (kof) [inline apps/builder/app/builder/shared/shortcuts/use-publish-shortcuts.ts:41]: Please stop using single-char variables and add a linter🙏
