### PR TITLE
Fix color input does not accept CSS color names

### LINKED ISSUE #1081: Color input does not accept CSS color names
Screenshot 2023-02-19 at 10 54 54 AM

We want the color input to accept CSS color names. https://www.w3schools.com/cssref/css_colors.php

The Webstudio default text color is "Black" so the text color input in the Typography section should show "Black", not a hex code or RGBA value.

### PR DESCRIPTION
**Pull request by istarkov**
## Description

1. What is this PR about (link the issue and add a short description)

Found few bugs.

- [x] - White color have border
- [x] - Fix transparent - all is parsed well its `react-color` feature
image

- [x] - Synchronize picker color and color shown in input

closes #1081

`+` Added transparent color (need be in design, looks better for most inputs if anything is shown)

image

image

Accessibility is not done fully for the color picker https://github.com/webstudio-is/webstudio-builder/issues/1092

## Steps for reproduction

1. You are now able to select colors by name
image

2. Colors with non-1 alpha will be shown on chessboard

image

## Code Review

- [ ] hi @kof, I need you to do
  - test it on preview

- [ ] hi @TrySound 
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)

## Before requesting a review

- [x] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [x] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-builder/blob/main/apps/builder/docs/test-cases.md) document
- [x] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

File: apps/builder/app/builder/features/style-panel/controls/color/color-control.tsx [hunk 1]
```diff
@@ -3,12 +3,26 @@ import { toValue } from "@webstudio-is/css-engine";
 import type { ControlProps } from "../../style-sections";
 import { ColorPicker } from "../../shared/color-picker";
 import { colord } from "colord";
+import { getStyleSource } from "../../shared/style-info";
+import { styleConfigByName } from "../../shared/configs";
+import type { StyleValue } from "@webstudio-is/css-data";
+import type { IntermediateStyleValue } from "../../shared/css-value-input";
+import { useState } from "react";
 
 export const ColorControl = ({
```
Comment (kof) [inline apps/builder/app/builder/features/style-panel/controls/color/color-control.tsx:12]: Think about how a color picker with the same logic could be reused with props panel

Comment (istarkov) [reply apps/builder/app/builder/features/style-panel/controls/color/color-control.tsx:12]: Probably can't as of now it will be simple wrapper around CSSValueInput because CSSValue input already has most logic we need.

Comment (istarkov) [reply apps/builder/app/builder/features/style-panel/controls/color/color-control.tsx:12]: Also for what attribute we will need color picker?

Comment (kof) [reply apps/builder/app/builder/features/style-panel/controls/color/color-control.tsx:12]: CssValueInput should also become usable over props, why would we miss an opportunity in a component to allow passing some CSS property?

Comment (kof) [reply apps/builder/app/builder/features/style-panel/controls/color/color-control.tsx:12]: we already support color control in props, storybook supports it too, any property can choose to accept a color, there is absolutely 0 doubt about the need for it

File: apps/builder/app/builder/features/style-panel/shared/color-picker.tsx [hunk 2]
```diff
@@ -1,19 +1,33 @@
 import { useState } from "react";
-import { colord, type RgbaColor } from "colord";
+import { colord, extend, RgbaColor } from "colord";
+// eslint-disable-next-line import/no-internal-modules
+import namesPlugin from "colord/plugins/names";
```
Comment (TrySound) [inline apps/builder/app/builder/features/style-panel/shared/color-picker.tsx:4]: I'd put it as an exception in eslint rule. Practically all modern packages with "exports" in package.json forbid to import internal paths when it's not part of api.

File: apps/builder/app/builder/features/style-panel/shared/color-picker.tsx [hunk 3]
```diff
@@ -1,19 +1,33 @@
...
+
 import { ColorResult, RGBColor, SketchPicker } from "react-color";
```
Comment (TrySound) [inline apps/builder/app/builder/features/style-panel/shared/color-picker.tsx:6]: We need to switch to react-colorful some day. From colored author.

**Comment by taylornowotny** [comment]
This was designed and is in our Library file: https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?node-id=947%3A3697&t=YbyBjl2FmEu8U93I-1

Screenshot 2023-02-20 at 11 02 04 AM

Please align with the design

**Comment by taylornowotny** [comment]
transparent swatch

Here is the checkerboard SVG that was designed

File: apps/builder/app/builder/features/style-panel/shared/color-picker.tsx [hunk 4]
```diff
@@ -50,83 +72,49 @@ const colorResultToRgbValue = (rgb: RgbaColor | RGBColor): RgbValue => {
...
-    // In case of blur, just reset to external value
-    setIntermediateValue(undefined);
-  };
 
-  const stringValue = intermediateValue?.stringValue ?? toValue(value);
-  const rgbValue = intermediateValue?.rgbValue ?? rgbValueToRgbColor(value);
+  const rgbValue = styleValueToRgbColor(intermediateValue ?? value);
+
+  // @todo transparent icon can be better
+  const background =
```
Comment (kof) [inline apps/builder/app/builder/features/style-panel/shared/color-picker.tsx:104]: lets replace it with the design from figma since we already have it

**Review by kof — APPROVED** [review]

**Comment by kof** [comment]
No idea how Rgba got there, can't bring it back in, maybe it was old data and new logic? no idea, not very important

File: apps/builder/app/builder/features/style-panel/controls/color/color-control.tsx [hunk 5]
```diff
@@ -1,27 +1,37 @@
...
 import type { ControlProps } from "../../style-sections";
-import { ColorPicker } from "../../shared/color-picker";
+import {
+  ColorPicker,
+  CssColorPickerValueInput,
+} from "../../shared/color-picker";
 import { colord } from "colord";
+import { getStyleSource } from "../../shared/style-info";
+import { styleConfigByName } from "../../shared/configs";
+
```
Comment (TrySound) [inline apps/builder/app/builder/features/style-panel/controls/color/color-control.tsx:11]: newline between imports?

File: packages/eslint-config-custom/index.js [hunk 6]
```diff
@@ -52,6 +52,7 @@ module.exports = {
           "@lexical/react/*",
           "__generated__/*",
           "react-hot-toast/headless",
+          "colord/plugins/*",
```
Comment (TrySound) [inline packages/eslint-config-custom/index.js:55]: `colors/**`

**Review by TrySound — APPROVED** [review]
