### PR TITLE
Fix scroll reset in style panel

### LINKED ISSUE #1617: Style panel scroll resets when selected instance changes
See https://discord.com/channels/955905230107738152/1104421616005435412

- May also happen when background is added (although I couldn't reproduce)
- Also "Select an instance on the canvas" flashes for a brief moment

### PR DESCRIPTION
**Pull request by rpominov**
## Description

1. Closes #1617

Before this PR `selectedInstanceIsRendered` behaved like this:

Switching to instance that **is** on canvas: `true -> false -> true`
Switching to instance that **is not** on canvas: `true -> false`

Issue: we can't tell apart brief `false` in the first case, and final `false` in the second

After this PR:

Switching to instance that **is** on canvas: `true -> undefined -> true`
Switching to instance that **is not** on canvas: `true -> undefined -> false`

Now we can distinguish temporary `undefined` from permanent `false` and don't hide style panel during `undefined`

## Steps for reproduction

Case 1:

1. Select a Box instance
2. Scroll style panel
3. Select another Box instance
4. Scroll should not reset

Case 2:

1. Select a Box instance
2. Select a Success Message instance in a Form
3. Style panel should show "Select an instance on the canvas" message 

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
- [ ] hi @istarkov, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-builder/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

File: apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx [hunk 1]
```diff
@@ -142,6 +143,18 @@ export const WebstudioComponentDev = ({
...
+    if (instanceSelector.length === 1) {
+      // If by the time root is rendered,
+      // no selected instance renders and sets `selectedInstanceIsRendered` to `true`,
+      // then it's clear that selected instance will not render at all, so we set it to `false`
+      if (selectedInstanceIsRenderedStore.get() === undefined) {
+        selectedInstanceIsRenderedStore.set(false);
+      }
+    }
+  });
+
```
Comment (istarkov) [inline apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx:157]: I would describe cases then it happens. As I don't understand why this logic is placed on Root (Body?)
Why it should be rendered at all and why execute useEffect on every render. What if some optimisations will be applied and this rendering will never happen?

Comment (rpominov) [reply apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx:157]: Ah, yes. This actually relies on `useStore(selectedInstanceSelectorStore)` above in the component. We rely on re-render after `selectedInstance` change

File: apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts [hunk 2]
```diff
@@ -192,19 +188,7 @@ export const SelectedInstanceConnector = ({
...
-      // This rare issue is difficult to reproduce, occurring roughly once every 100 calls.
-      if (
-        areInstanceSelectorsEqual(
-          selectedInstanceSelectorStore.get(),
-          instanceSelector
-        ) === false
-      ) {
-        selectedInstanceIsRenderedStore.set(false);
-      }
+      selectedInstanceIsRenderedStore.set(undefined);
```
Comment (istarkov) [inline apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts:191]: I would give a link to webstudio-component useEffect here

File: apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx (hunk 1 above)
Comment (rpominov) [reply apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx:159]: Added code comment

File: apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts (hunk 2 above)
Comment (rpominov) [reply apps/builder/app/canvas/features/webstudio-component/selected-instance-connector.ts:193]: Addded

**Review by istarkov — APPROVED** [review]
I will accept, as of now we have no idea how component decide what to render.
But this looks super error prone. 
Any optimisation could kill current solution

File: apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx [hunk 3]
```diff
@@ -142,6 +143,20 @@ export const WebstudioComponentDev = ({
...
+    // 1 means root
+    if (instanceSelector.length === 1) {
+      // If by the time root is rendered,
+      // no selected instance renders and sets `selectedInstanceIsRendered` to `true`,
+      // then it's clear that selected instance will not render at all, so we set it to `false`
+      if (selectedInstanceIsRenderedStore.get() === undefined) {
+        selectedInstanceIsRenderedStore.set(false);
+      }
+    }
+  });
```
Comment (kof) [inline apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx:158]: this is executed every single time, shouldn't it rather have dependencies, e.g. instanceSelector

Comment (rpominov) [reply apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx:158]: The code inside is very light. Checking dependencies can be even slower

File: apps/builder/app/shared/nano-states/nano-states.ts [hunk 4]
```diff
@@ -233,8 +233,13 @@ export const selectedInstanceIntanceToTagStore = atom<
   undefined | Map<Instance["id"], HtmlTags>
 >();
 
-/** Whether or the selected instance is rendered on canvas */
-export const selectedInstanceIsRenderedStore = atom<boolean>(false);
+/**
+ * Whether or not the selected instance is rendered on canvas:
```
Comment (kof) [inline apps/builder/app/shared/nano-states/nano-states.ts:237]: This sentence is confusing, maybe the variable name is confusing with this semantics?

Kinda can't use "is" if its not boolean, you need to change the name

Comment (kof) [reply apps/builder/app/shared/nano-states/nano-states.ts:237]: seems like better name here would be: "selectedInstanceRenderState": "mounted" | "unmounted" | "something else" ?

Comment (rpominov) [reply apps/builder/app/shared/nano-states/nano-states.ts:237]: Ok

File: apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx (hunk 3 above)
Comment (kof) [reply apps/builder/app/canvas/features/webstudio-component/webstudio-component.tsx:158]: the danger is that someone can add more to the code without realizing it's going to run every time
