### PR TITLE
Fix collapse on size change

### LINKED ISSUE #1183: Collapse detector fails on initial load in this particular case
Screenshot 2023-03-06 at 23 49 54

Link to page in DM

Steps

1. open debug page
2. on initial load collapse detector sets both vertical and horizontal paddings
3. if you change any CSS property, it detects correctly and padding goes away
4. after reload it will be back

### PR DESCRIPTION
**Pull request by istarkov**
## Description

closes #1183 

## Steps for reproduction

1. click button
2. expect xyz

## Code Review

- [x] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [x] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [x] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-builder/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

File: apps/builder/app/shared/dom-hooks/use-window-resize.ts [hunk 1]
```diff
@@ -65,3 +65,16 @@ export const useWindowResize = (onResize: () => void) => {
     };
   }, [onResize]);
 };
+
+export const useWindowResizeDebounced = (onResize: () => void) => {
+  useEffect(() => {
+    // Call on leading
+    emitter.on("resizeStart", onResize);
```
Comment (istarkov) [inline apps/builder/app/shared/dom-hooks/use-window-resize.ts:72]: Can be called twice but above we have todo - add throttling, but better to make debounce with leading and trailing edges.

**Review by TrySound — APPROVED** [review]
