### PR TITLE
Fix page settings

### LINKED ISSUE #1061: Updating page title and name stopped working
When you try to rename page title or page name, it just reverts them back in a second

### PR DESCRIPTION
**Pull request by rpominov**
## Description

Fixes #1061 .

## Steps for reproduction

- Try to rename page title or page name
- It should not revert back in few seconds

## Code Review

- [ ] hi @TrySound, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)

## Before requesting a review

- [x] made a self-review
- [x] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-builder/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

File: apps/builder/app/builder/features/sidebar-left/panels/pages/settings.tsx [hunk 1]
```diff
@@ -342,9 +342,34 @@ export const PageSettings = ({
 
   const fetcher = useFetcher<EditPageData>();
 
-  const [pages] = usePages();
+  const [pages, setPages] = usePages();
   const page = pages && findPageByIdOrPath(pages, pageId);
 
+  // Updating client side store like that is a temporary solution
+  // We want to switch pages to immerhin: https://github.com/webstudio-is/webstudio-builder/issues/1084
+  const updateAtClientSide = (page: Page) => {
```
Comment (kof) [inline apps/builder/app/builder/features/sidebar-left/panels/pages/settings.tsx:350]: maybe updateOnClient

**Review by kof — APPROVED** [review]

**Review by TrySound — APPROVED** [review]
